FROM eclipse-temurin:25-jdk

WORKDIR /app

COPY .mvn /app/.mvn
COPY mvnw mvnw.cmd pom.xml /app/
RUN sed -i 's/\r$//' /app/mvnw && chmod +x /app/mvnw
RUN /app/mvnw -q -DskipTests dependency:go-offline

COPY . /app

EXPOSE 8080

CMD ["./mvnw", "-q", "spring-boot:run"]
