FROM eclipse-temurin:25-jdk AS builder

WORKDIR /build
COPY .mvn /build/.mvn
COPY mvnw mvnw.cmd pom.xml /build/
RUN sed -i 's/\r$//' /build/mvnw && chmod +x /build/mvnw
RUN /build/mvnw -q -DskipTests dependency:go-offline
COPY src /build/src
RUN /build/mvnw -q -DskipTests package

FROM eclipse-temurin:25-jre

WORKDIR /app
COPY --from=builder /build/target/*.jar /app/app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
